title: "FoggyKitchen Autonomous Database Serverless with Terraform - LESSON 11 - Creating Autonomous DB Serverless with Remote Autonomous Data Guard."
description: "This lesson explores a cross-region Autonomous Database Serverless deployment with a private endpoint and a remote standby database protected through Autonomous Data Guard."
stackDescription: "This lesson explores a cross-region Autonomous Database Serverless deployment with a private endpoint and a remote standby database protected through Autonomous Data Guard."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid

- title: "Required Configuration"
  visible: true
  variables:
  - compartment_ocid
  - adb_password
  - primary_region
  - standby_region

variables:

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your OCI tenancy"
    type: string
    required: true
    visibile: false

  primary_region:
    title: "Primary Region"
    description: "Choose the primary region for your OCI Autonomous Database Serverless deployment"
    type: oci:identity:region:name
    required: true
    visibile: true

  standby_region:
    title: "Standby Region"
    description: "Choose the standby region for your OCI Autonomous Database Serverless deployment"
    type: oci:identity:region:name
    required: true
    visibile: true

  adb_password:
    title: "ADB ADMIN Password"
    description: "Specify the password for OCI Autonomous Database Serverless ADMIN user"
    type: password
    minLength: 12
    maxLength: 30
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment"
    description: "Choose compartment for OCI Autonomous Database Serverless"
    type: oci:identity:compartment:id
    required: true
    visibile: true
